#!/usr/bin/env python3
"""MANARA sample test set helper (Pillow only).

  python3 tools/manara/samples.py data            rebuild site/manara/assets/samples/samples-data.js
                                                (320-px-wide JPEG data URIs, so the detector test bench
                                                can read pixels from file:// without a tainted canvas)
  python3 tools/manara/samples.py rgba            write every image of samples-data.js as raw RGBA to stdout:
                                                for each image a header line "<file> <width> <height>\\n"
                                                followed by width*height*4 bytes. Used by tools/manara/test-fire.mjs
                                                so Node scores exactly the pixels the browser bench sees.
  python3 tools/manara/samples.py rgba photos     the same for the extra photos in tools/manara/photos/
                                                (listed in photos/labels.json: 'tuning' and 'test' sets)

The list of files comes from samples.js (window.MANARA_SAMPLES), so the two never drift apart.
"""
import base64
import io
import json
import os
import re
import sys

from PIL import Image

# Paths follow this file's folder name (tools/<name>/ <-> site/<name>/), so renaming the project folder needs no edit.
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
DIR = os.path.join(ROOT, 'site', os.path.basename(HERE), 'assets', 'samples')
DATA_JS = os.path.join(DIR, 'samples-data.js')
PHOTOS = os.path.join(HERE, 'photos')
WIDTH = 320
LIMIT = 600 * 1024


def sample_files():
    src = open(os.path.join(DIR, 'samples.js'), encoding='utf-8').read()
    return re.findall(r"file:\s*'([^']+)'", src)


def build_data():
    parts, total = [], 0
    for f in sample_files():
        im = Image.open(os.path.join(DIR, f)).convert('RGB')
        h = round(im.height * WIDTH / im.width)
        im = im.resize((WIDTH, h), Image.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, 'JPEG', quality=78, optimize=True)
        uri = 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode('ascii')
        total += len(uri)
        parts.append('  %s: %s' % (json.dumps(f), json.dumps(uri)))
        print('%-12s %dx%d %6d bytes' % (f, WIDTH, h, buf.tell()), file=sys.stderr)
    js = ('/* MANARA sample images as small (320 px) data URIs — generated by tools/manara/samples.py data.\n'
          ' * Lets the detector test bench read pixels from file:// (a canvas fed from a file:// <img> is tainted).\n'
          ' * Credits and licences: CREDITS.txt in this folder. */\n'
          'window.MANARA_SAMPLE_DATA = {\n' + ',\n'.join(parts) + '\n};\n')
    open(DATA_JS, 'w', encoding='utf-8').write(js)
    size = os.path.getsize(DATA_JS)
    print('samples-data.js: %d bytes (limit %d)' % (size, LIMIT), file=sys.stderr)
    if size > LIMIT:
        sys.exit('samples-data.js is larger than %d bytes' % LIMIT)


def emit(out, name, im):
    im = im.convert('RGBA')
    out.write(('%s %d %d\n' % (name, im.width, im.height)).encode('ascii'))
    out.write(im.tobytes())


def write_rgba(which):
    out = sys.stdout.buffer
    if which == 'photos':
        for item in json.load(open(os.path.join(PHOTOS, 'labels.json'), encoding='utf-8'))['images']:
            emit(out, item['file'], Image.open(os.path.join(PHOTOS, item['file'])))
    else:
        src = open(DATA_JS, encoding='utf-8').read()
        for f, b64 in re.findall(r'"([^"]+)": "data:image/jpeg;base64,([^"]+)"', src):
            emit(out, f, Image.open(io.BytesIO(base64.b64decode(b64))))
    out.flush()


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else ''
    if cmd == 'data':
        build_data()
    elif cmd == 'rgba':
        write_rgba(sys.argv[2] if len(sys.argv) > 2 else 'samples')
    else:
        sys.exit(__doc__)
