"""Build site/data/kb.js — the brochure as a searchable knowledge base.

Loaded on every page as a classic script (works on file:// too) and shared by
the search overlay (js/palette.js) and the assistant's offline answers
(js/chat.js). Schema (contract — add fields, never rename/remove):

window.TAKAMUL_KB = {
  version: 1,
  pages: [{id, url, title, icon}],
  items: [{
    id,        # 's3', 's3-1', 'p4', 'st2', 'f1', 'b3', 'welcome', 'toc'
    type,      # 'section' | 'subsection' | 'pillar' | 'stage' | 'faq' | 'intro'
    num,       # display number: '3', '3.1', '4', 'س1' ... ('' if none)
    title,     # verbatim brochure heading / question
    subtitle,  # verbatim sub-heading ('' if none)
    text,      # verbatim brochure lines joined with '\n' (bullets without markers)
    url,       # deep link: 'initiatives.html#s3-1'
    page,      # 'initiatives.html'
    section,   # parent section number (int) or 0
    group,     # FAQ group: 'founders' | 'board' | ''
  }]
}
"""
import json

from core import D, L, LS, PAGES, SECTIONS, SITE, toc_items

SUBSECTIONS = [  # (anchor, heading line, first body line, last body line, section)
    ('s2-1', 56, 57, 71, 2), ('s3-1', 76, 77, 81, 3), ('s3-2', 82, 83, 87, 3), ('s3-3', 88, 89, 96, 3),
    ('s4-1', 100, 101, 112, 4), ('s4-2', 113, 114, 125, 4), ('s7-1', 171, 172, 183, 7), ('s7-2', 184, 185, 187, 7),
    ('s7-3', 188, 189, 203, 7), ('s8-1', 207, 208, 221, 8), ('s8-2', 222, 223, 226, 8),
    ('s13-1', 379, 380, 445, 13), ('s13-2', 446, 447, 498, 13),
]
PILLARS = [306, 314, 323, 330, 334, 342, 348, 354, 363, 367, 375]  # start lines (+ end sentinel)
FAQ_F = [381, 386, 399, 408, 412, 420, 427, 435, 439, 446]          # question-number lines (+ sentinel)
FAQ_B = [448, 452, 464, 468, 474, 478, 485, 492, 499]


def text(a, b):
    return '\n'.join(t for t in LS(a, b) if t and t not in ('◄',))


def build_kb():
    items = []
    page_of = {}
    sec_order = sorted(SECTIONS)
    for idx, n in enumerate(sec_order):
        num_l, title_l, sub_l, page, _ = SECTIONS[n]
        end = SECTIONS[sec_order[idx + 1]][0] - 1 if idx + 1 < len(sec_order) else 498
        page_of[n] = page
        items.append(dict(id=f's{n}', type='section', num=L(num_l), title=L(title_l), subtitle=L(sub_l),
                          text=text(sub_l + 1, end), url=f'{page}#s{n}', page=page, section=n, group=''))
    for anchor, h, a, b, n in SUBSECTIONS:
        items.append(dict(id=anchor, type='subsection', num=anchor[1:].replace('-', '.'), title=L(h), subtitle='',
                          text=text(a, b), url=f'{page_of[n]}#{anchor}', page=page_of[n], section=n, group=''))
    for k in range(10):
        a, b = PILLARS[k], PILLARS[k + 1] - 1
        items.append(dict(id=f'p{k + 1}', type='pillar', num=L(a), title=L(a + 1), subtitle=L(a + 2),
                          text=text(a + 3, b), url=f'join.html#p{k + 1}', page='join.html', section=12, group=''))
    for i in range(7):
        items.append(dict(id=f'st{i + 1}', type='stage', num=L(130 + 4 * i), title=L(131 + 4 * i),
                          subtitle=f'{L(129 + 4 * i)} {L(130 + 4 * i)}', text=L(132 + 4 * i),
                          url=f'expansion.html#st{i + 1}', page='expansion.html', section=5, group=''))
    for group, starts, prefix in (('founders', FAQ_F, 'f'), ('board', FAQ_B, 'b')):
        for k in range(len(starts) - 1):
            a = starts[k]
            b = starts[k + 1] - 1
            if prefix == 'f' and k == len(starts) - 2:
                b = 445
            items.append(dict(id=f'{prefix}{k + 1}', type='faq', num=L(a), title=L(a + 1), subtitle='',
                              text=text(a + 3, b), url=f'faq.html#{prefix}{k + 1}', page='faq.html',
                              section=13, group=group))
    items.append(dict(id='welcome', type='intro', num='', title=L(9), subtitle=L(1), text=text(10, 11),
                      url='index.html#welcome', page='index.html', section=0, group=''))
    items.append(dict(id='toc', type='intro', num='', title=L(12), subtitle=L(1),
                      text='\n'.join(f'{n}. {t}' for n, t in toc_items()), url='index.html#toc',
                      page='index.html', section=0, group=''))
    items.append(dict(id='closing', type='intro', num='', title=L(499), subtitle=L(500), text=L(501),
                      url='join.html', page='join.html', section=0, group=''))
    kb = dict(version=1, pages=[dict(id=f.split('.')[0], url=f, title=t, icon=i) for f, t, i in PAGES], items=items)
    (SITE / 'data').mkdir(exist_ok=True)
    (SITE / 'data' / 'kb.js').write_text(
        '// Generated by tools/build_kb.py from content/brochure.txt — do not edit by hand.\n'
        'window.TAKAMUL_KB = ' + json.dumps(kb, ensure_ascii=False, separators=(',', ':')) + ';\n',
        encoding='utf-8')
    return kb


if __name__ == '__main__':
    kb = build_kb()
    print('kb items:', len(kb['items']))
