#!/usr/bin/env python3
"""Build the Takamul website from content/brochure.txt.

    python3 tools/build.py            # site/*.html, site/data/kb.js, worker/knowledge.js
    python3 tools/check_content.py    # verify every brochure line is on the site

Modules (see docs/ARCHITECTURE.md): core.py (shell + components), pages.py
(page compositions), dashboard.py (command center), build_kb.py (search/chat KB).
"""
import json

from core import D, HEADER_LINE, ROOT, SITE
from build_kb import build_kb
from dashboard import build_dashboard
from pages import build_pages


def build_knowledge():
    """Worker system-prompt knowledge (the whole brochure)."""
    text = HEADER_LINE + '\n' + '\n'.join(D[:501])
    (ROOT / 'worker').mkdir(exist_ok=True)
    (ROOT / 'worker' / 'knowledge.js').write_text(
        '// Generated by tools/build.py from content/brochure.txt — do not edit by hand.\n'
        f'export const KNOWLEDGE = {json.dumps(text, ensure_ascii=False)};\n', encoding='utf-8')


if __name__ == '__main__':
    build_pages()
    build_dashboard()
    kb = build_kb()
    build_knowledge()
    print('built', sorted(p.name for p in SITE.glob('*.html')), '| kb items:', len(kb['items']))
